name: ci

on:
  push:
    branches: [main]
    paths-ignore: ['rw']
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-latest

    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact_id }}

    steps:
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v14

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and Test
      run: make test

    - name: Build for WebAssembly
      run: emmake make clean build-wasm

    - name: Upload GitHub Pages artifacts
      uses: actions/upload-pages-artifact@v3
      id: upload
      with:
        path: site

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      env:
        GITHUB_SHA: ${{ needs.ci.outputs.artifact-id }}
      uses: actions/deploy-pages@v4
